Include URL in library information
cybozu/LicenseList pull request #21
Opened 2023-11-15 05:42 UTC by SNQ-2001

Closes #20 

# Usage
https://github.com/cybozu/LicenseList/assets/84154073/21d4bcf8-9ce2-4776-b886-c1d605c2282c

```swift
import SwiftUI
import LicenseList

struct ContentView: View {
    @Environment(\.openURL) private var openURL

    var body: some View {
        NavigationStack {
            List(Library.libraries) { library in
                NavigationLink(library.name) {
                    Text(library.licenseBody)
                        .padding(.horizontal, 16)
                        .navigationTitle(library.name)
                        .toolbar {
                            ToolbarItem(placement: .topBarTrailing) {
                                Button {
                                    if let url = library.url {
                                        openURL(url)
                                    }
                                } label: {
                                    Image(systemName: "link")
                                }
                            }
                        }
                }
            }
            .navigationTitle("License")
        }
    }
}
```

2023-11-21 02:54 UTC, Kyome22 requested changes

2023-11-21 02:54 UTC, Kyome22 commented on Sources/LicenseList/View+Extensions.swift
> +    func navigationBarRepositoryAnchorLinkIfPossible(action: @escaping () -> Void) -> some View {
There is no need to add IfPossible to the name of this function if the same functionality can be provided regardless of iOS 14 or later.

----------

iOS 14以上でもそうでなくても同じ機能が提供できるなら、この関数の名前に`IfPossible`をつける必要はなさそうです。

2023-11-21 03:05 UTC, Kyome22 commented
I think it would be better to add usage instructions to the README.

~~~md
### Example for UIKit

```swift
import LicenseList

// in ViewController
let vc = LicenseListViewController()
vc.title = "LICENSE"

// If you want to anchor link of the repository
vc.licenseListViewStyle = .withRepositoryAnchorLink

navigationController?.pushViewController(vc, animated: true)
```

### Example for SwiftUI

```swift
import LicenseList

struct ContentView: View {
    var body: some View {
        NavigationView {
            LicenseListView()
                // If you want to anchor link of the repository
                .licenseListViewStyle(.withRepositoryAnchorLink)
                .navigationTitle("LICENSE")
        }
    }
}
```
~~~

2023-11-21 04:49 UTC, SNQ-2001 commented
@Kyome22 
Fixed!

2023-11-22 04:42 UTC, Kyome22 commented on Sources/LicenseList/View+Extensions.swift
> +    func navigationBarRepositoryAnchorLinkIfPossible(action: @escaping () -> Void) -> some View {
[a46e505](https://github.com/cybozu/LicenseList/pull/21/commits/a46e505dc8d0dfa513f4b18cbd1eaec5886a67b7) fixed

2023-11-22 04:42 UTC, Kyome22 approved these changes
LGTM

2023-11-22 04:43 UTC, merged